 3107713 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2831893 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 3096331 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2775569 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2363169 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2746723 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2661715 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2625842 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 2787292 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
 3001074 : <<lambda>() takes exactly 2 arguments (1 given)> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector.py", line 55, in get_vector
    res=method(movie)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
 
